In [49]:
import torch
import pandas as pd
from torch import nn
from d2l import torch as d2l
import numpy as np
import os
from PIL import Image
import albumentations
from albumentations.pytorch.transforms import ToTensorV2
from torchvision import transforms
from IPython.display import display
import torch.utils.data as Data
from sklearn.model_selection import StratifiedKFold
from sklearn.preprocessing import LabelEncoder
train_path = '../data/train.csv'
test_path = '../data/test.csv'
image_path = '../data/'

df = pd.read_csv(train_path)
labels_unique = df['label'].unique()

class LeaveDataset(Data.Dataset):
    def __init__(self,data,lable,file_path,transform=None):
        self.data = data
        self.label=lable
        self.transform = transform
        self.file_path=file_path

    def __getitem__(self, index):
        data_path = self.data[index]
        data = np.asarray(Image.open(os.path.join(self.file_path,data_path)))
        if self.transform :
            data=self.transform(image=data)['image']
        label = self.label[index]
        return data, label
    
    def __len__(self):
        return  len(self.label)

le = LabelEncoder()
df['label']=le.fit_transform(df['label'])
kfold = StratifiedKFold(n_splits=5,random_state=42, shuffle=True)
df.shape
for k, (train_index, valid_index) in enumerate(kfold.split(df['image'],df['label'])):
    #train_data,train_label=df['image'][train_index],df['label'][train_index]
    print(train_index,valid_index)
# le = LabelEncoder()
# le.fit(df['label'])
# df['label'] = le.transform(df['label'])
# label_map = dict(zip(le.classes_, le.transform(le.classes_)))
# label_inv_map = {v: k for k, v in label_map.items()}
# df['image']

[    0     2     3 ... 18350 18351 18352] [    1     4     8 ... 18319 18323 18348]
[    0     1     2 ... 18349 18350 18352] [   12    14    16 ... 18341 18342 18351]
[    0     1     4 ... 18350 18351 18352] [    2     3     5 ... 18343 18344 18345]
[    1     2     3 ... 18350 18351 18352] [    0     7    11 ... 18339 18346 18349]
[    0     1     2 ... 18348 18349 18351] [    6     9    13 ... 18347 18350 18352]
